In [63]:
import pandas as pd 
import numpy as np
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt 
import seaborn as sns

In [64]:
df = pd.read_csv('treated_v1.csv')

In [65]:
#profile = ProfileReport(df, title = 'Pandas Profiling Report',explorative=True)
#profile.to_file("Output_report.html")

In [66]:
pd.set_option('display.max_columns', None)

In [67]:
df.head()

,PROP_ID,PROPERTY_TYPE,SOCIETY_NAME,CITY,location,BEDROOM_NUM,BALCONY_NUM,AREA,Price_per_sqft,PRICE,AGE,FACING,FURNISH,amenity_luxury,FLOOR_NUM,LATITUDE,LONGITUDE,PROP_NAME,TOTAL_FLOOR,FORMATTED_LANDMARK_DETAILS,DESCRIPTION
0,J71214794,flat,Bhawani Bandhan,Kolkata North,Madhyamgram,2.0,NaN,920,4239.0,0.39,Old Property,0,Unfurnished,NaN,1,22.690003,88.459080,Bhawani Bandhan,11.0,"['5 Religious Places', '15 Hospitals', '1 Attr...",Experience a new style of living with Bhawani ...
1,F70835394,flat,Ganguly 4Sight Desire,Kolkata South,Garia,1.0,NaN,535,5100.0,0.27,Old Property,0,Unfurnished,NaN,1,22.468780,88.380720,Ganguly 4Sight Desire,7.0,"['3 Metro Stations', '9 Religious Places', '3 ...",Let your dream of owning a flat come true with...
2,P69854924,flat,Dtc Capital City,Kolkata East,Rajarhat,4.0,NaN,1940,4742.0,0.92,Old Property,0,Unfurnished,NaN,1,22.562087,88.505528,DTC Capital City,20.0,"['1 Shopping', '1 Education', '1 Hospital', '1...","Book your 4 BHK apartment in DTC Capital City,..."
3,E69854912,flat,Dtc Capital City,Kolkata East,Rajarhat,2.0,NaN,910,4615.0,0.42,Old Property,0,Unfurnished,NaN,1,22.562087,88.505528,DTC Capital City,20.0,"['1 Shopping', '1 Education', '1 Hospital', '1...",Make DTC Capital City your next home. Book you...
4,R69167152,flat,Sai Sarovaar,Kolkata East,New Town,3.0,NaN,1163,4700.0,0.55,Old Property,0,Unfurnished,NaN,1,22.570830,88.483880,Sai Sarovaar,4.0,"['1 Metro Station', '1 Religious Place', '1 AT...",Book a spectacular property in Sai Sarovaar th...